name: liblk
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest mypy
          pip install -e .
      
      - name: Lint with Ruff
        run: |
          ruff check liblk tests examples
      
      - name: Type check with MyPy
        run: |
          mypy liblk
      
      - name: Run tests
        run: |
          python -m pytest tests/